//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBDMessenger
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages_mes
    {
        public int message_id { get; set; }
        public Nullable<int> sender_id { get; set; }
        public Nullable<int> receiver_id { get; set; }
        public byte[] content { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
