//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBDMessenger
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessengerDTEntities2 : DbContext
    {
        private static MessengerDTEntities2 context;

        public MessengerDTEntities2()
            : base("name=MessengerDTEntities2")
        {
        }

        public static MessengerDTEntities2 GetContext()
        {
            if (context == null)
                context = new MessengerDTEntities2();
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chats> chats { get; set; }
        public virtual DbSet<messages_mes> messages_mes { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
